name: CI - Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  qa:
    name: Quality Assurance
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Earthly
        uses: ./.github/actions/setup_earthly

      - name: Build, lint, test, and run diagnostics
        run: earthly --ci -P +build-app

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Run Prettier
        run: test -z $(yarn prettier:check)

  linting: 
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint:check
