name: CI - Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  qa:
    name: Quality Assurance
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Earthly
        uses: ./.github/actions/setup_earthly

      - name: Build, lint, test, and run diagnostics
        run: earthly --ci -P +build-app