name: Build and Deploy Docker Image

on:
    push:
        branches:
            - main
            - dev
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Determine version
              id: version
              run: |
                  if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
                    echo "::set-output name=version::$(jq -r '.version' package.json)"
                  el
                    echo "::set-output name=version::$(jq -r '.version' package.json)-rc.${{ github.sha }}"
                  fi

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/od-app:${{ steps.version.outputs.version }}
