name: Document PR
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  label-packages:
    name: Label packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: banyan/auto-label@1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  label-size:
    name: Label PR size
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: 'pascalgn/size-label-action@v0.4.3'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          IGNORED: '!.gitignore\nyarn.lock'
